language: node_js

node_js:
 - "node"

cache: npm

script:
  - npm run build

before_deploy:
  - cd dist

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  
